apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:DBKCSMH2PORwDKZ0u1JANfS9nxp8N0jYW4yg9GBo1oLwIRbkdGXVD4RpNdG1RBzzLgPoPMZdOGfa4uDT7m7vJr3z9tZ0XxQVFI0=,iv:5rpos+7ZEisG3vu8aRlBPFXNp2F2+GEb0bUR0kiWNDY=,tag:wd5p2TttupxSeoGCfaf7EQ==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:nAywqjnycM6J5RL7O7HyHvA07wa+A0WKGAjXNrjMn/fZYeLse++vPdcE5bGAY/HvTWlaHA==,iv:VO4wDeHbDziS7VxQIETYFzkVmBaca52MtYtkYe139MY=,tag:tMRshc3n+uuHtq7+R8Yx+Q==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMHdHVnlPYWVZWEoydXh2
            T0FDRTFWZHdzOVNkRUZ3Y1o5b3NZN3NVNG1JCkV4Uk5xODI1L0Nad3N4K25QcDdC
            RXRIczhqSHowQWxUOGVwOFpPT1dOY0UKLS0tIHNHMXY5TG5qKzNzYTVTWDF5OTFu
            RlZBZEtZOEhJcHdUaWxCanA3V3psaE0KCy7HsVR5tA5Pfly9JwpzkiRtYLWFlpEc
            bkggpQefRGgnfAaxCol+G8NRGOwBgG/Cys3aiqgg/8RpziOTLyrisg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T11:05:50Z"
    mac: ENC[AES256_GCM,data:fAUZCMQz7Gx0oMKN+g2HoGksvRP67uLbJGRYwxdTxY3jDc9nVBws+JW4bJ7l7djjHQgnF71HSsw3Xn8EePi6cfuGd2aM0cb/5tlaICBrF5dDaqC8fBsmArouHhOJWlAEIHnx9YlaKZu5mlqCRk8xlD+gfkkDIxPlkHILG6UEGIg=,iv:kYQBcsVJtfrX9zPbjNgC079KkpYBXJ5/h2a5SnWgGvw=,tag:RwFXJJZPI77J07xiz/1F6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
