apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:/RzbZcS6iAvm24FFA/hcMh35xi2e/HHdJ0+wJf/7c3WONm3Cfa99C+NXxRiz5crti0h3bsBdhuPD/L0iTpUEwKTZID0=,iv:PO6J+RBIlYEyBYiHqAje+onvMJci0lIV3/grx6gKnLk=,tag:6qSfWop03Faphegw0KDarw==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:NjB5ZrabUYKj8gM+1ThMjY9o0yGLK7CkXR4aUXebmGGBB3vRAsDxiAn0YR81JDEel0fXxME=,iv:A+SCGiI435L+KcrQpVt3rhy/HqtzRRVN6QyJl/mDTrw=,tag:i6MOU2mAE7fgyV1QR0NQcg==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVDBiWmxrTGtpYnIxUURG
            Qlg2NEtvZGZnS0x2VXlQNVZ5WkhicUxmK0FjCnBSK2VnWGtCWUE3RlM5bVR6WnEv
            RFg5cUk4c1dRazcwTWF4V0g3dUI2VXMKLS0tIHpTQjJPb0l4YWhIYlJLQVlIbWZF
            cWw5OTRnTnZZVE1xVmhNdkVlTXU1UTgKp7/NoRFaDjikVb2Is9KU3zpvD5WXrxtV
            7F8ZFJSsPTtRALfphz0tGLtSJqvu61MG4xLRR4hIOOwCqmT240HT8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T10:33:19Z"
    mac: ENC[AES256_GCM,data:TIDuDKbkrTjHAyEsYXN1GMjKK5Cu4/D/eLNHzV7OwQJJhF+0NCBt5MLGu/RK81MYLfa/JfSyg/Jqoo8X76JwBfFpQP87sTIyJ+Z40Td5/SqU97vrgc+JvAI/yxacYwBMTdGg0UwRFcoKCFgaely6MBVb+nQKgDA3P9QUj1HB6DM=,iv:d7LlWD1rbDCTInk0CRobEG8vrEl0UEEPGnCvvdL/39g=,tag:CqQI5POeJrFUk18hcxEuIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
