apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:YPJ7mkbPsQp5QnVBs1cfXtCExRks3sXitn35u16lNZr/5SPU0KEX/PvSKZG9JnjcmvoPec5MeKB3c//pHbNTq+FzbaS91yQzZfP4fzt46rE=,iv:LlJYPJcW3ai0Bvn/kDhq4QzKCQS/jB/vpskHjgel8tQ=,tag:52Oi8nl6j0aoIwB0pYyJLw==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:mGwA9Kx4UaDOjfq3/7paWN8NFNg69KD/ZsLtJM/4bvUTmWX2dtAH+VSHAE/TCaPYEPyKdIo=,iv:61+BrfvOKtYv6QVkAxaR/sFzcOZDJBkQGEYoYTmR7c4=,tag:H9+5la7xNmlAroW8dt+KRA==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U0hHNnVEQXpZa3NsTkw3
            Tk9ZdjBVamZaN2sraXY0UWxmektRV3lCQ1dJCmNTR1ZOWW9BVXYyNEZKMGQvSWVT
            SW5NNVpLTUMraVhrZk5ub3B3M3VON0EKLS0tIHZTQkcrWUpNTm1MN0FtaEgyZ2U4
            NEpGejl3Nm5VaVJtbkJYTmJCUUNPNGsK6/erkAZ/AQDjpZR8R01CMP6YJkFrlnZN
            1tx9ElMeeKyzKK662xR3GyHzbF8AXM+6uNrZT3CNnTfpYiXRiBe8mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T11:39:14Z"
    mac: ENC[AES256_GCM,data:St59McFVMpRzEE97hq3kvMHV8+eUpAZLKgL+aNIrS6GxgBBQ8GAs2v2RqmzahEFj1LErWT33SFVsJx22UtI1AC25uZo+UvtrOyVy2b1jrU05GIiTVbuu3vFBJ0qzN0ogZ/Q9RpD4luIjj/A9NwK161sLqNCJC6LkO7IeTUeQRDE=,iv:vxG6NnrP9A8RoQzWuj9LdhXzkBE92JI/FLErXe44y2o=,tag:r9gGWZ2XY4GOHkpgAT+BMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
