apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Z/EKxcoKGItvPZ0Awp6mHGM04yJuc9sNrfL2XA==,iv:2o2VZiLPPxgq1mpIwP8xRn9s7yyBE2vvwtvj9oTfh9A=,tag:amauILWcIADzjxnyvvZWOA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:rN+r7w1mAr8cGBmN99rvaQ==,iv:39mhaOFwrx1sA7GqDzUbQCTdQg/+EJ4bHc6mGSNsdmQ=,tag:9ybJyvP+lg+ZCUe27LDEIA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data://6IRdeuGsfjEIHB+Wx5YzcNaQGrlWmMdatBvgYNOkdWA9j7w71DEbvaT3Yq8amzfQkfDo9SpCs=,iv:bru7HBDAWBXXWfjcO4Syzq4Dj2cqVA+s7WlEgXFo7kY=,tag:m9ZCROcc2BDMRFU6pljaWg==,type:str]
kind: Secret
metadata:
    name: aws-secret
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbHlDa2F1WUFSeDZvWEQ2
            QnU2YjFzdU1LMDBsZEcyVTlQdVVDVklYeUR3Cm5ZdDZZc0dMTmJ4YTkrNDZ5S2Fj
            NU85NjY4MjFFT2dWdURXSzBWZmd4V0UKLS0tIDNjZ0JkNkZYK3NZaU5yeVNrZzhJ
            RjllZXZLOTY5dEFOcHc2ODhaZ3B5cTAKbEt+qz2XwUspgniYOCyixf8IhDq6G8lP
            2LsY+k3asLFUougVMlESA/OgguNMYc+PByp5vebUtHYVH1vaMUo8Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T21:51:58Z"
    mac: ENC[AES256_GCM,data:bEgU//csaPPMIkUmeZ8wrwpAVyEhhUsAMFvdw6pOUteelXfYYsUbenfoUpi2Iaxw8C8xkZKxzQS3uC0W17dBCbUkQkQdvPJ3tyL9KTIucZDXjkEl5Deux5z/avunNbaxX+sqN9GtwNOmoA7kxRaJpJjb/+6/uycA8JJAthLM+3g=,iv:nxJTy6JbQWHCkEVaNhdBnp1JTNFAxpS5PhDXuO+DWdQ=,tag:D6KfCr0sUrfRh8IBp7iNcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
