apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gHprFhf3wbypwdWY073PGZFiNTM=,iv:VKMzouGGr7EVghLJgmiIaH+U+DwfbYvvWat0Y5VXSPg=,tag:nlyjECLeUb+VNzV/g6p1oQ==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:YnFhKUE6E0CD11w1,iv:KEpKvTnb17ZMQvhbDYKly6BMgJExkU09agHvfoqUZ48=,tag:hEu//E/XpOBfqFAfqfwZug==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NdYd+SuhtgSHNrme2nZGV/4/4yWt3CpkMG3cG/CEdwX1waU+OfE16g==,iv:QOVaFjZRtougrv5RYvHjx5BSeeF2yoyfSXxKn0BisqA=,tag:RLsWiBYEwKvYuS8f2aMbBQ==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdzZ3OG5seEFKTktPZDV0
            enliVCtoVHZib3JkbURld2ZBMm9rdTR4ZEhJCnhHUytDUFU4OGNXdUlyV3d2RkhD
            Z3c2K1UzN3RwV1BpdDJFSkgxTmZ4RG8KLS0tIGdrSDZoR2NYRWkwOUQ5aXV2OEJM
            SGl4ZGt6V2RvU3BXVHB4Q21wT21sNzQK2oc9PB9Sga93nPl5YMfsG3e64feNiHpj
            JUpVUVQiAzXFMuw+lPbqKEfISYl9w3gWWfF0oASiCbe//0kyU5hvOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T20:34:52Z"
    mac: ENC[AES256_GCM,data:vf9ob0YSmhnAVIXF29Wo1r6goW17vo5Fu4QArePjRfZUNEiqwA3EMUwrlmksG67VA0YqrplgGhynSczOlxB0X4z1sy/9HyiRU9GwHyTBlRmHMQ0cOpjh/JUld8aebcpI+SV1bIbbyCjAMpEUECFzAMMDiKob5Y/iNU1nYPB4n5I=,iv:9qbfejXT9j1f7+yqQHrDWbovha3MyoRPlXnuJ/tVkks=,tag:dv513aYGWYkmHemvLQwT4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
