apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VqugOQxOQUlyaucNq9+gl1x61ik=,iv:WfwvdabwTgjAcm8OXehJJqyJbA7KKiom1PM4idYH9vA=,tag:mFcogget8DkAfN1r0af1Ug==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:6yVRVYu6vtJEORDA,iv:q6MtZpflBru53KtbPJNtH7qAi8jhWXc/BZxXU14SNIE=,tag:KkXXEJ7KzQqGkU9DIyctFQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+fqsev/6NMOhm44Kokwk+azghwPD/z6D2Cx2hu++PLFzMqdDa+maLA==,iv:375lh4zqpDM9Z/OX2Lx0ophyuHd+va+b1lTQx124bTc=,tag:Vo35Qi0mUnHpQ1Wq7Oa8BA==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOHR2VTU4cDlJT21VMzlp
            VVA3KzlUZzlxRG82VDFRKytiL01HY3R6SlZFClVDaTdYMDRNTTZlcjkvcFhYMkVv
            aWdoa3hWQlczUStOSitiRjVnd0JhOU0KLS0tIEJjQnJCQ3lPT2xaTndUeGxXR0hj
            Zk8wakcxZHE1bkE1eW5xZG9jZmN0TlEKRAVmtFgzflJ5R2nEaIXqrbo+8t55eCUw
            BurbMKFxM7dsjgIrSTZZtwHjPXcZFsBuGspcXDppj0+kl3Aw8w3MQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T11:52:57Z"
    mac: ENC[AES256_GCM,data:n8r6cWTgDJzpxeTLZYK/L7f/7gzsTre6Az8lVh3ow33WMCE1JvHeQny9tD/xNVfcDnYk3LnjgD8yDdvDTa4EvNMoIyToAG61mx6jd+WSlPytzlQe9qBgO5M01iBe29x0mTna/HCvoL7vE8RRaKmiEueFYtAq4xuvTRwlEEvMc70=,iv:sntqKOkMz8f1DOMnbFz5XJLRPIHtsRGg2RwjaLH6XKc=,tag:UMEB0WLlXxDqmldSvalnqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
