apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgrzyt-backend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgrzyt-backend
  template:
    metadata:
      labels:
        app: zgrzyt-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: zgrzyt-backend
          image: ghcr.io/mikolajbielinski/zgrzyt-backend:main@sha256:1429a63123e9b83851c90c1d74d6d839198a2d6f5156b5f29822811f1849c678
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: zgrzyt-backend-config
            - secretRef:
                name: openai-secret
          livenessProbe:
            httpGet:
              path: /limits
              port: 8000
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /limits
              port: 8000
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /limits
              port: 8000
            failureThreshold: 12
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zgrzyt-backend
spec:
  selector:
    app: zgrzyt-backend
  ports:
    - port: 8000
      targetPort: 8000
