apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgrzyt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgrzyt-backend
  template:
    metadata:
      labels:
        app: zgrzyt-backend
    spec:
      containers:
        - name: zgrzyt-backend
          image: ghcr.io/mikolajbielinski/zgrzyt-backend:main@sha256:735ba53db192485bd481328b23a9fe6b6175209d92ac9e7e12deeafe086e8b7e
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: zgrzyt-backend-config
            - secretRef:
                name: openai-secret
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zgrzyt-backend
spec:
  selector:
    app: zgrzyt-backend
  ports:
    - port: 8000
      targetPort: 8000
