apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zgrzyt-backend
spec:
  podSelector:
    matchLabels:
      app: zgrzyt-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: zgrzyt-frontend
      ports:
        - protocol: TCP
          port: 8000
