apiVersion: batch/v1
kind: CronJob
metadata:
  name: zgrzyt-download-newest
spec:
  schedule: '0 * * * *'
  timeZone: Europe/Warsaw
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: zgrzyt-download-newest
    spec:
      activeDeadlineSeconds: 1800
      backoffLimit: 2
      template:
        spec:
          automountServiceAccountToken: false
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: ghcr.io/mikolajbielinski/zgrzyt-download:main@sha256:2cd191c02f00bb6fa6a7808cc3a2ca5c032f87658efac0ed6436ea946b70cd29
              name: zgrzyt-download-newest
              volumeMounts:
                - mountPath: /podcasts
                  name: zgrzyt-podcasts
              envFrom:
                - configMapRef:
                    name: zgrzyt-download-newest-config
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 1Gi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
          imagePullSecrets:
            - name: ghcr-secret
          volumes:
            - name: zgrzyt-podcasts
              persistentVolumeClaim:
                claimName: zgrzyt-podcasts
          restartPolicy: Never
