apiVersion: batch/v1
kind: CronJob
metadata:
  name: zgrzyt-embed
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: zgrzyt-embed
    spec:
      template:
        spec:
          containers:
            - name: zgrzyt-embed
              image: ghcr.io/mikolajbielinski/zgrzyt-embed:main@sha256:e053129fb39115b0e03e58b917a8a894876b0257aa9e642bc9a3336184133503
              envFrom:
                - configMapRef:
                    name: zgrzyt-embed-config
                - secretRef:
                    name: embed-aws-secret
                - secretRef:
                    name: openai-secret
          imagePullSecrets:
            - name: ghcr-secret
          restartPolicy: OnFailure
