apiVersion: v1
kind: Secret
metadata:
    name: embed-aws-secret
    namespace: zgrzyt-ai
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7boHBz3DsGVnyx78gL3SAPgL+Vo=,iv:q34Xky51HPQfyYKy1W5DO2MGnA1WJ8LjuFQ8rmCuILE=,tag:/NVCOalHm621NfiaF5dqRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Cw9cwvau/nsgGn7I3kZ2KtRYa0OIBI/7DpFYeLT/rXRGSToEApUKQA==,iv:xneq4uCwqKNSXCSzjNtqqLj0hWvdvcDrz51EfiZrh+k=,tag:jtJic2+AjvPie1V4Cppsfg==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:z8gAjGBUyfJ3jv3p,iv:kQDuKeMz7DE81qvctappk4mAkatEqGCVRhTocPct3po=,tag:r5jvA+fPBJwkTyF+o4y1jg==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V2FPd2g1ZjRKaWZlbDJC
            VHJCMSt0Tk9NRytDNGxDaXduNTQxdmZuem40CkV1SWN2eDhWTmNVQVNaVFRqazFu
            YmdOaHZreCtKbHBHWWw4MG1xWm5BMFEKLS0tIG0weE1yRmxaOENTRVBoSm5ZUUJI
            T1ZkQzdqdGF6TUZVZE1TUFNxNTBjb1kKGQ+eF/s8b1+yl+a4HIbFR/3naU+JXI5r
            fO7dnIBhIOEeQeD6PftRyL2qVM2jUxGRUEKVJEX00W5TAMRcpi1acA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T17:12:39Z"
    mac: ENC[AES256_GCM,data:FF4fD73aJAXwHmBzdkRwpWZqhjYaGWfw1xCwKDj+y9Y7ciggsiPm5J7ZKfBzMwVWWQ8Kz5n2UBwBON1GPhicWgbI5ZkLoVhinxKOghW8UJDDSV7ZUwez+zQzvYjAfz+rVt5UGc1pWwHbSJaR2FLS6qpwD1KyB8hnGXRrMT2cE9g=,iv:acItS1Bo3vpKEkv6VGtuHTDSAGQAEzJzRVP/Nc+A+Co=,tag:FSV8y5lJ1NiC9DuGIw+Qyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
