apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgrzyt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgrzyt-frontend
  template:
    metadata:
      labels:
        app: zgrzyt-frontend
    spec:
      containers:
        - name: zgrzyt-frontend
          image: ghcr.io/mikolajbielinski/zgrzyt-frontend:main@sha256:8c9dc4363e6ef2d25982a25f27f44976c1f4cb0c7f15c78f17c1afac25ac4890
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: zgrzyt-frontend-config
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zgrzyt-frontend
spec:
  selector:
    app: zgrzyt-frontend
  ports:
    - port: 80
      targetPort: 80
