apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgrzyt-frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgrzyt-frontend
  template:
    metadata:
      labels:
        app: zgrzyt-frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: zgrzyt-frontend
          image: ghcr.io/mikolajbielinski/zgrzyt-frontend:main@sha256:7a00aafce7b28136401b9e4fe7109393ce066ca3a8cb981edae5076958cb6099
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: zgrzyt-frontend-config
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 12
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zgrzyt-frontend
spec:
  selector:
    app: zgrzyt-frontend
  ports:
    - port: 80
      targetPort: 80
