apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:lwk65xE0BXTWI8ACUaboUWaBBp4HKx4bdb4I6wu5cZ66knnB6RHkl4hlTkXWiHtdeVhjsHnjHqD0V7BXyZvZO4SNXZcMdLmJDX2bAcJ0RfG+kyUqyGZQxrTxvqi77nQSQOrqSa2n5SayD1KeHnJ8PgfSbjjv6L/6OIXNogCg1JnLWLttoFdkza9dxcLp+Lqr3gFMo/KAJ8dPA5voNg9120SV7l8uv9klxmdjUduNVzEJZ+z0arQT9EY/HzejaCQXgphAX4h8Kt877fR9mtcUQDMJdAeTa4MbVNNOc3CnSRU1Rk9DUzDnUVJc+21IP/VMy2CNLmlEp70pO2dfZ/+CcjZga+o=,iv:qPR5Ho3B1dJx1F7nK9/T869Z6OoV/V4LUvYv7PbV6XM=,tag:VsZWBqLjWuMbp/Ah8tbEKg==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YWRUR3huOGpUUWNNUlFl
            WFBlTGYxRjlUWjV6VXVUSDdPMEYwODFmQ0ZjCmxCQkR4dStsSG5RRjF3REFQNDJT
            Mk5ySTBpVHUxZisvbXdtdVpBQkJ3WXcKLS0tIDNaM2xQZ2ZES1RSWU1URVR5NEE4
            QXk0M0lqcU5IdCszOHVnTkdKT2Zla0kKM04o3QpEOQcKrXHhuBEkvUU255yoXdax
            qFnGKfZ3sMc/pgUjLmyMLV9ehNQyjeSC5JB4N/EXxMLu1NkIIrJUpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T11:14:20Z"
    mac: ENC[AES256_GCM,data:n7AhkTMWXgnmeBM28+e7HsbPx/ByE2D27+BIdVpfB34saN/0dcTaMHQRFsBcKo38rW7EAqvtnDow5RJhldK0m9dRr3apANJKyjJKCK5tAVzax0SRM/RdBjBfvhym0JiP5oEsnIRtaukkXPUag+h/hIFWEceu4kzamNAeMU14WYA=,iv:6S8LZnpXWnOhyOMYyJBR8vvT/gQH+0swDHHryJYkHz0=,tag:XnU+rKUely6DhGBUIKvGBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
