apiVersion: batch/v1
kind: Job
metadata:
  name: zgrzyt-download-all
  namespace: zgrzyt-ai
spec:
  template:
    spec:
      containers:
        - name: zgrzyt
          image: ghcr.io/mikolajbielinski/zgrzyt:latest
          volumeMounts:
            - mountPath: /podcasts
              name: zgrzyt-podcasts
          envFrom:
            - configMapRef:
                name: zgrzyt-download-all-config
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: zgrzyt-podcasts
          persistentVolumeClaim:
            claimName: zgrzyt-podcasts
      restartPolicy: OnFailure
