apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-secret.yaml
  - storage.yaml
  - configmap.yaml
  - cronjob.yaml
  - reconciler-configmap.yaml
  - reconciler-cronjob.yaml
  - aws-secret.yaml
  - openai-secret.yaml
  - qdrant-repository.yaml
  - qdrant-release.yaml
  - embed-configmap.yaml
  - embed-storage.yaml
  - embed-cronjob.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-ingress.yaml
  - speakers-deployment.yaml
  - speakers-secret.yaml
