apiVersion: v1
kind: Secret
metadata:
    name: openai-secret
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:hO2gWU2NZsjtl/ruTUKweWVJmC+6nkSCaruWB17mcYR1rFRHQ/AQ+3uoui0in99+A6vwcEBs9s09+GqzyT0dHkbnZ2EmvWjEE/VPoPFLk77XL2Mlp6tdpU5htG8a0LCohfQBinw6qwq1Q5V2reBeBmldHykiPjA6lQOqtc99DsmyUsvH/P8QsvFvYoSfU2pGqcUvTNiOBBWsrQBjrsTIx7Xr0VU=,iv:K9OvUrLYhRZv5oLLDUfMUd9dw1hh3tAIJfH7jd+AqfY=,tag:hoPp7HkU7pux9tSEZFeguA==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VmgwMWtXeFlPRmE3cDJR
            bzlOWFYybjYreXFYNnR3NXVWYUs4MS8zNEY0CmcyZHV1THZURThLeDZNRW5TTXBj
            cS85em1vZDIxVVF0REpPWkhZb1dDQlUKLS0tIEMxNlNKQkJuZExod1Y5cWdoZnpa
            NW9SbWNIY0lkayt1VUcxbEJQamM5Mk0K+48bjCsR60RUQyvDHtiCQq7bxgdNx+f9
            FRIrn3lF4xuWbtZf4NOoBs1dtX3frTh5lhg35bdrZcUWwNYfv+LekA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T22:00:47Z"
    mac: ENC[AES256_GCM,data:TT13vD9/OQWm7LfGsJnISkdd14GRal3p97rLNM10hEkZJkIJFG3b4R8mIpFRoY8fdy2pOHWU6bHJUYvLYUcW/GQoZ9WydaBuWrbzoTpN0YvrDzqaUmP6UYfgpFLJ8aBIHxF7S9qTM+N3/BVHIOID33u0DPSmpYAEu8VKtYLmBV8=,iv:7GjM73HHRsNxt9sMNAmPik3CZ6SNlBtg0aJRylkNoww=,tag:bvO8W3rZQbre7bfSCWiSDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
