apiVersion: v1
kind: Secret
metadata:
    name: orchestrator-secret
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qLZmyKihXzKs9h6SKmfAKOeF4uU=,iv:7vkhWl/eZiBQjUWIvHJh/d1fg1lwaa0fnNRglkrHANA=,tag:Wq5ufWEVDgi6p/ooTggzfA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vzgMI/1FXVCEfOFTVOpyXpAlWYjuLgyMwhhDCbd0uEGH9g0/w5FIdQ==,iv:Nm2VQ5Rs0xdvOhZfFAeUFGfEC+31gyz7yWroKrgBD4E=,tag:K+8b0qyi+ki9NL3XWBm7uw==,type:str]
    NTFY_TOKEN: ENC[AES256_GCM,data:lWKPO8tE0jWVy4xF5YT7DfzqQPoW1DnuiS1uBUMd66o=,iv:p8/zp2tqI4gZtaI/m/KLBncrBvQvg0beh7789AFPbSU=,tag:AhO/W5OCYSeUHqbrESLXmw==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaTBpQ1k5eEt4YmJzd0Mx
            b2RhYTllTUxCOFJ5YjlaOWRJUlZ0bXNMK2tRCndrRHJNR0FBWVB1dDdYQ01GTytX
            MHdXYzhReHkwOE1LaER5YUVkTmhBR28KLS0tIE4weWR5aUxHUitDaTRMQ1dVby9C
            NVRxT1FGbWtmNS90eGFNSWtXTGZnN3MKxziksP6zc4HZKpHKZSwVYct56TiVIcRk
            V7Xs+pVPiQGaO2qMWuZFgRccgrcJfI8VHdPMQM6kKw3DvVFf8SXfVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T13:02:01Z"
    mac: ENC[AES256_GCM,data:wQq7+qPyZeJf8TqphzPFxKA646rxlil5bNqXXo3qJ5PH/Cvov2EBXvFXUTUKnVj9qM3ulo/yIlj5AVU905lfANvCyWwfdEu6FPoHyfdzHSe4OHa8XRa6l6tfdTdRt8re0XdUhMUA9KmSxXyuhVoGwW52ue534RB7QBR04lVxs+w=,iv:JFvtXi+/8adGKVr2AGcCETftO08TwXqfOIu6+gz2PqI=,tag:gM1PTP8sqNlr2IDOcJQj9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
