apiVersion: batch/v1
kind: CronJob
metadata:
  name: zgrzyt-orchestrator
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: orchestrator
              image: ghcr.io/mikolajbielinski/zgrzyt-orchestrator:main@sha256:429b62e1c9e19018021010dc4a010782e550d0b7ffa9f68115a47c1ccbcc822e
              envFrom:
                - configMapRef:
                    name: zgrzyt-orchestrator-config
                - secretRef:
                    name: orchestrator-secret
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  memory: 256Mi
          imagePullSecrets:
            - name: ghcr-secret
