apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: zgrzyt-ai
spec:
  interval: 30m
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: StatefulSet
              name: qdrant
            patch: |
              - op: add
                path: /spec/template/spec/automountServiceAccountToken
                value: false
              - op: add
                path: /spec/template/spec/securityContext/seccompProfile
                value:
                  type: RuntimeDefault
              - op: add
                path: /spec/template/spec/containers/0/securityContext/capabilities
                value:
                  drop:
                    - ALL
              - op: add
                path: /spec/template/spec/containers/0/livenessProbe
                value:
                  httpGet:
                    path: /healthz
                    port: 6333
                  failureThreshold: 3
                  periodSeconds: 30
                  timeoutSeconds: 3
              - op: add
                path: /spec/template/spec/containers/0/startupProbe
                value:
                  httpGet:
                    path: /readyz
                    port: 6333
                  failureThreshold: 60
                  periodSeconds: 5
                  timeoutSeconds: 3
  chart:
    spec:
      chart: qdrant
      version: '0.10.1'
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: zgrzyt-ai
      interval: 24h
  driftDetection:
    mode: enabled
  values:
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 1536Mi
      limits:
        memory: 3Gi
