apiVersion: v1
kind: Secret
metadata:
    name: reconciler-aws-secret
    namespace: zgrzyt-ai
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0QQOxISwnKno6nQzuuddd5VtjpI=,iv:tvqedIbeQN9NYu9JPiHJ6WCk6MbiEFtwxf1QeS8NaGM=,tag:j/Ts2vjwaO45CnuXKJAqRw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AeREAu1pLq+NNdHO6zW8gJcFB6nzndYBPGdUHG21KOoK6UiA5w3F0w==,iv:ywEOyXTHO+D+XU3mkCeD1LO53lry/hgqNqGtKX3FiLA=,tag:9bly8JvTz3t9dcGEA90EIA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:zRRL29I7GXiPxg4f,iv:CUTH+weRuqhroKjXZC04CaWWkYmVV4ez51KOszTpPK4=,tag:TD7h9r6EpYd/8RfhyOZULQ==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQUR4R3VkcE9SaVNBcVUr
            QmxXVVFzd2J0aGZDY3NkQjc2bWI1SUF5R1VvCkE2Y3FDWGtXekluUjA2ZEJpenFl
            QXZzRllIQVdUanRLUkJaZUxSTGpvRzgKLS0tIGViZHozUyt3TldHZzVYZTdaTFhF
            TEZLSzQraUppcmFDZm9HcEZETFNWeW8K1rL+JAamcdErzdfAYJx5FGJXVmyzhGEf
            VglG/469Jlghueu1BVrKJZVFOC9Cl4bIP9nQZ8mm7sheVWhgT2pT3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T17:12:39Z"
    mac: ENC[AES256_GCM,data:3b1NkbVvElpAkJwFcfG0x3sd3Wn1S8WtyhlSMsW8DD6mDEOYGKSObrISrumLnR4038VCBy9INzlFMjnd+6nfz3/nx8ITLS9T3MKqrRysPQgvHyyUkPUo0DcCk8vlLdd5bFpukdneGtR+i13jdNU/NNVGCj6Ca3Hb2mWwqIrKkBo=,iv:WMsNyjXxsNimZieNKIFqOl60K54aDSHeQVVM3VOGVhM=,tag:wNAX2HE6YbpwzkOsHEG04A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
