apiVersion: v1
kind: Secret
metadata:
    name: speakers-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CRWbz6nXJsL+CLRnsP6HR24tIWg=,iv:eNM3tFdZqqbF86j2JJfi7d3fvdWr8iR83kh4e0uYgj0=,tag:VTbGCmmKJoaeSy8jL6jm2g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gOAhhlT92PAlet5UIJaQJYhbZRsfJUpMTf3edq1ZVcGnM4GnKMFApg==,iv:NcJMIvynK94uCJmFgs17Y5iD2pSaUrs1wMlkVWi4j/E=,tag:Ej7XhgYvyOB95TF44Kqmvg==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:pDZgjl2fJo2J,iv:0qV2EZosb6MvHbGVEYFdE0RbxtCOO7rGROUkKGP9fZg=,tag:5/WQtIDSlCictwZMj5CAog==,type:str]
    APP_USER: ENC[AES256_GCM,data:kybsXw17L3g/5Q==,iv:6V1wg1odSp3qNUXNTOET2TzVAHtq/jiQUYJcsKyAVAE=,tag:Ly1RoffAgTntDAa2q/a5cg==,type:str]
    APP_PASS: ENC[AES256_GCM,data:MI4oS9oQmAVoNPlfVEaAZlV4KuQ=,iv:H2zOYLsU3WIwwgBozsLXmiHPKq8DHBtOvXWtI4l/29U=,tag:yDjbDKOkoOY33KXvxk1euQ==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:X2cB5Wl7rDAli0Voj9WqFuzpbvIgWycGRzOaWpTAUg9TrGmdJfBVuQYo97Q=,iv:eckiHrEHmMw9LZ6VyFBtZ3Z7dLeRigEXCwZQCwiq3Lg=,tag:9cGJ55dm2j4zOQXu1j/L6A==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:DM8abVTjDLWPoi8=,iv:ivf4F3SvZ89aDWEyD8/0Ks3gOiVZXIqnrUPo2a26WAU=,tag:TjlAwj5Hlsww9G9j2WtO1g==,type:str]
    BASIC_AUTH_PASS: ENC[AES256_GCM,data:5+DqAozbBXd86Xx2,iv:Z9NO/OHk0UmNovllV5u6tw8UbOsc6QchVGmzRI1x1eE=,tag:0w1Pi00PEnq7QHRQQvcVFA==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK2ZvT20xOG1ubk41bWdN
            MHNxaHZIeXNvNnRLUFRTOWNkaUlPNlhqa3lBCnZXc1RkblNnVnBzRUVxTlV2RExK
            T0lPRzI4bDErK2kvMnZzWEl4MHN6NVUKLS0tIDNkUDB5KzlXaTljN0ErR2t1Vm9F
            bXJwRm51TzZtcm1XUWFGSmlkbWw0WWcK9VKaxVZGIsPlmdQGaywEGk0uDUt3uJ1J
            PmasoDmLyUJKI46dPXPvfR9m/J0pzMn6/nT+RtNUEE/5foHlBa9pZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T09:36:57Z"
    mac: ENC[AES256_GCM,data:P8fglmcFiYkv5kVwdvKv0KpODGBiy96Nc1598Q+/xUF7HEGML6OBJupuK8uC0V/NIg1nVr+xZcFjUS8QxdrvnbYciMjBLXyjTxT4ApNsTmQKFGKQlbnqFoFHs607Wti6NgggfFSeWvEjrBdJbH6lXeGefFcM7BYifn8PJnXMAX4=,iv:ZeMhB1eJ/rgLjbzMP7RPgRkHyHCJdhov0sMYt45h9NY=,tag:5C1gcOOW4k7d5BnYVWyoPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
