apiVersion: v1
kind: Secret
metadata:
    name: speakers-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yU8gQjIYWqQGyQ0R5CEPWtXG1to=,iv:V7cnTw0lMTgnPxGizEd60qpLUm2kCj/2GCSNoh4M39E=,tag:ks9VWngYm+zYS4s5tQsqIg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gcU0a46tathnASoE4C1bLn/ku+19zB/mv/THVxT7CK0/ZXdz9j+evQ==,iv:sn3pLNCT1mN1pt+G+/I/IPclr33D+09zUHbenufcxww=,tag:TtSNxPpScY7TJYp4RgzN3Q==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:CYNiIP8KKDri,iv:1dkLZ295EsYyz3he0sgCP0UjLT7cIQw+il66d/IupAE=,tag:TqNjeu5jbWIFrBrxUrKYxw==,type:str]
    APP_USER: ENC[AES256_GCM,data:gGzZQCteIbRv5g==,iv:A5puy3nEYCYNqeuKVzSzzplGziIOaaq4gD6R/2TGg4Q=,tag:hfBSDl2lIBrQTt1/OSe3GA==,type:str]
    APP_PASS: ENC[AES256_GCM,data:ScQbfzNqSg6tgm2izJUFPIT24w4=,iv:u/CpBqNwaOJl7OHdp6NZPSDhrNdK84b8Sh/sdmVnEHA=,tag:9OEGLXGCY62Ureh57abaUw==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:m7mI9kkDp9MyrF1LiiXJolMDZvu47q12Nvcoj3gyMKkq5IixGuN6nMQekWA=,iv:2chpluw8uQobUX2f5F/tDogox7hd5yfp6h9ug43wjvo=,tag:trhQHMqKd581TBpd43Ehag==,type:str]
    BASIC_AUTH_USER: ENC[AES256_GCM,data:njeB1j2RpMsv8lY=,iv:X0hSXQ1cVxO5yqudeytEW/FiU1Lo5WKq2b2q6dXAvpM=,tag:R5LVOJWSlc7ztAQAgsw5YQ==,type:str]
    BASIC_AUTH_PASS: ENC[AES256_GCM,data:kiP2V8fM/Astwebv,iv:AssWbllO/h4EbLz/YgWD4u54zWw/oai9W+ut3dNdPKY=,tag:Wy9ySX2CTV0uZ7w2gZRuDA==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVmxDR0xCL01JWnM4QkVL
            UmhzZmhKSHkvR1hORjZpRjA0Tjd1VXFLdndzClkrZXJsMk9kcDlrZWN0SXZ6blZi
            S2dSSmJLT3VHUXpyWE8vRCtoWitDL2cKLS0tIFNpcFN3RTZFZno4N3RqTWJWUzlX
            Yis5bXRzMlNEUWZYNVM3RFNla204elUKXWtShsAH+XN+ccNrvh1HXo6S9aIexUC2
            FSe79xXysW7m4ID0K9TvfXlu71xb4G9fv6EAxOdhbK4SaOqc1SOwzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T17:13:24Z"
    mac: ENC[AES256_GCM,data:wPvjJhs7Gt1xY+QgljVE3row9hhZQQS8nTChw/wBxcSpHxknylIR6M5KwhpshJLZcpTysD6FQYj9Cz1XGY4KyWH6EkiitegGwlvoUIJRrAwqoIWwdo7YtspemgZ/Hw8nIMqi3HkvUjfVHP5+ojPxuQCUWyz7RCSvzoNf1r5/ZmA=,iv:b4Os0JKHN2yDtgZ4ZkaeToQ80bg0NJ/hJiBsSMQYy28=,tag:LnMgte4ckGtAsIAAjKiV5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
