apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgrzyt-speakers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zgrzyt-speakers
  template:
    metadata:
      labels:
        app: zgrzyt-speakers
    spec:
      containers:
        - name: zgrzyt-speakers
          image: ghcr.io/mikolajbielinski/zgrzyt-speakers:main@sha256:3ad8ffd8dd8c6b0bb62d96fed1a9733019110d834861d29a28e799cd58a1c7a5
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: speakers-secret
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zgrzyt-speakers
spec:
  selector:
    app: zgrzyt-speakers
  ports:
    - port: 5200
      targetPort: 3000
