apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:KT8ROTeLOkF7KimH3jlOltaammrwCLQWp7HNyW82gqjnYIxmANwnXF+A7DgTlOUAvHbVeNSvwlDtr/4Q8CS8AGdWTFbcLVcRb5omc9PFCRQH9+0M72XZ4tcClHrAw6kpZcO3x1NGWe6+qAmpc7sxAYebLXzZGV4AGdq8yZzBqId+3oLJYGh2zXpR4Ff0ztcFeLzlTC+yzxTxRO0/HPXImTrThwi0tFWxWQisXAPgp0wRhDuPpDKskE3s6GvMFVl0J3I4xW48tauCrl/JMqQd8cHkeFLDKDV4XBVsN/e6uui7IzAenY4xlvltaTE=,iv:zlCJzjJ9Wafe9vcFh6UhH4VLDjk4C83w7f3aAJPEiqo=,tag:sN1H/pQqv5eqOmQWZ6WHrg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSHQ3ZjMrQ3dOdWlMZjhq
            VlkyOUtvTWlzTEdzb01iaUZtVG9CNG00QWc0CkU5aVpxZmk5Sk1KU3hxNVBqVGZE
            ZVFRMzFvTGN5M2NzNzZKRkl6cERnS3cKLS0tIHdrTmpRaVcrSjI1MWtCWDNSQTJx
            ZW1WOCszWVo1L0V6VldraVBhdzgySGMK2mUCH5Sg4U+a52+ky35FvQN6Czy5u8zB
            vn/ublRz0WkQtz/s8GOxEu0a7Z1KI9gj/zC7Dej412fAUPlQHYdQHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T19:40:33Z"
    mac: ENC[AES256_GCM,data:qUVJF/Whats/4ff09G49aMR3jFQvlwKklC7n3694+2rVkFKxooD3Fq3/RWE+SJW1wUFb2kxjicQPj0NhCbNyBYkub4iJ82Ynv80mGg1FRU5kixAdg8A3yQPpn0xEtN2TMWnLdoC9yin1h2yIjiUvQdDRbWVHMLlgKcBHRveSkvM=,iv:a/W1UdYmXDP9Y1z0CljLqkLCiPEb+ZEACUE2NksliNk=,tag:O2IQd/cv3DwMlqCRZBM3Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
