apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:DsJO1tPv0V1uVSUOBLjYXAVIBrZ1okPgaWy29OQt5MW+m14cc7366GItbIcOsBEvLSsohU0qN7EA7g9ozhQvRsdcfTqAFdrDMtJ5+rIdEZWUMaWhYv3TDaFGHRCkYA7CsrArknC8WQAL7VEQgTAkj8lJJVCjo13P7XvXSwoTuH72mPA48SoNb/IZiNE/37NBPq0hrqYFg2IAXdkEuhya3oSUSAfAoUvXploeD6Yx5aKK/9rXgWgywTN7FXKPJSeNoJcsqbH+x7FIWrmo7dh4OMMMaV7kLJi3uzLHkxDN3QhaDvJ3DMIAJgLm3Vc=,iv:bxuJ85yJ1vB3KIM8wwvNt/ltt3gG83vbqCs41jHjrO8=,tag:RTT/Z8TAoydExNKKnG4Scg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxekRkV0pBVFRLamFqeWRK
            ZS83YzFEcXpKdXRNOWVKVjZXTlhsU0IxMVFNCmRtVExSRnloQ0s2OUhneGtRdmZk
            UlliZmt1RjEraGxuTzlMRmFMNVJUYUkKLS0tIGpnQnFoamt5Sk9aT2c4MTRQT2l0
            K2dPMHprVWFaWjRlN1p3dThlZTl0cGMKhm4mVtHS+TwSoD9RqlOakHyJrlRoceIo
            3jGbOMJ77G6+IGHqJbbaRwB2NKPybKoZ7MUm9XPGiZgjbsvKEcGYTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T18:46:19Z"
    mac: ENC[AES256_GCM,data:MaUHf85dLBVnH8SdMBbBSw6HKOpcrMQd3EXkjirW/JpudmZp9nhf/9LjCi5FH/NTWTx5ir8uST7Wyfhg55Q5Tw83QY8ryaIXwlo5FfvjPnolTBNgqM8Re5OE8sqlm+gjPX2TOvc2ZqDaQzfZ4BAI9yV7DorPhfYs7Vb85C2Iu88=,iv:QLENx2FtXq87OT1Dfxr3OvdznFFNditImzypYUwzXKU=,tag:iSdUpCBusmGMca55VOuJQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
