apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        - image: ghcr.io/advplyr/audiobookshelf:2.32.1
          name: audiobookshelf
          ports:
            - containerPort: 3005
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: audiobookshelf-config
          volumeMounts:
            - mountPath: /audiobooks
              name: audiobookshelf-storage
              subPath: audiobooks
            - mountPath: /podcasts
              name: audiobookshelf-storage
              subPath: podcasts
            - mountPath: /config
              name: audiobookshelf-storage
              subPath: config
            - mountPath: /metadata
              name: audiobookshelf-storage
              subPath: metadata
      volumes:
        - name: audiobookshelf-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-storage
