apiVersion: v1
kind: Service
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  ports:
  - name: 3005-3005
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: audiobookshelf
  type: ClusterIP
status:
  loadBalancer: {}
