apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-storage
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
