apiVersion: batch/v1
kind: CronJob
metadata:
  name: upload-backups
spec:
  schedule: 0 23 * * *
  jobTemplate:
    metadata:
      name: upload-backups
    spec:
      template:
        metadata: {}
        spec:
          containers:
            - image: rclone/rclone:v1.75.1
              name: upload-backups
              volumeMounts:
                - mountPath: /backups
                  name: backups
              envFrom:
                - secretRef:
                    name: aws-secret
              command:
                - /bin/sh
                - -c
                - rclone copy /backups :s3:homelab-lynx-backups/backups --s3-provider=AWS --s3-env-auth --s3-region=eu-central-1
          restartPolicy: OnFailure
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: backups
