apiVersion: batch/v1
kind: CronJob
metadata:
  name: upload-backups
spec:
  schedule: 0 23 * * *
  timeZone: Europe/Warsaw
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 21600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800
      activeDeadlineSeconds: 3600
      backoffLimit: 2
      template:
        spec:
          automountServiceAccountToken: false
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: rclone/rclone:1.75.1
              name: upload-backups
              envFrom:
                - secretRef:
                    name: aws-secret
              command:
                - /bin/sh
                - -c
                - >-
                  rclone copy /backups :s3:homelab-lynx-backups/auto-backups/
                  --s3-provider=AWS
                  --s3-env-auth
                  --s3-region=eu-central-1
                  --s3-no-check-bucket
                  --exclude "*.partial"
                  --exclude "**/.ssh/**"
                  && rclone delete /backups
                  --min-age 14d
                  --include "*/upload/**"
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  add:
                    - DAC_OVERRIDE
                    - DAC_READ_SEARCH
                  drop:
                    - ALL
              volumeMounts:
                - mountPath: /backups
                  name: backups
          restartPolicy: Never
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: backups
