apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - secret.yaml
  - cronjob.yaml
  - deployment.yaml
  - secret-ssh.yaml
  - configmap.yaml
  - service.yaml
