apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kwdJ6fPAn61cr8z9Kv8ssWgg/gtBvH+1q36GFg==,iv:k0MD13Lof9rSThJcXkp2m6YPv+9uVV3U3sFeVNu9VF4=,tag:nxkdtm2YQ4Frx25EHkTmdg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FoU/SopNErxk7q7Kthawz0snD4DcZm3YqzifEmWnx02sxtMT6VYtr36y7OTmbdITn7jB1gu9MNc=,iv:vaGTlyBKCU5AkS/wI47rO1WFGPNr4hTqH3R07gXOHtc=,tag:wHeJqSmAgWJyrYGwgLS6ag==,type:str]
kind: Secret
metadata:
    name: aws-secret
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL0FQZUkwVjREWU15aTN2
            QUR5U2dZZzE4VDdzbUFyRVByL3FrM2tUaTF3CkVwQ1kwTjNVNGlNdlhjaHl0ajZj
            NDcxVW9oR1FVbk9xakZBRWdHS29GWU0KLS0tIGhhdGNGNzBpdmpNeHp2RW8yR3oz
            b2lORjVqU25mdnlaV1Fvc3BTRmU1MkkKg1YcG4D3Hz8yjarMZATnvQA7GRSqwJSY
            TGaswMXjbT2AVYOZuDI/wntI5Tur23tmwKDKCTY0lC2Ds1z5dt0Tgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T19:50:03Z"
    mac: ENC[AES256_GCM,data:YCKLETLZkfKDmlYNgEIuStC1zYOJ7bnYKzzlgge0STNG+uq4Xuisu42ZbPWolWVAgWC1Q36WsmxeRL4jMEbkiKHNpSnoTX3+SUL/v8ekgQ0erQtpoB6NNGNXfg7fn8XKIFO88/Lo4EMVxyGW2J5p1eub/+9vRuirVmzGrbeyhYY=,iv:3zhCos3TtLghWo/Scodr2YZi9wA5CkLvwaTFIIQjsRc=,tag:dftksc0WHHcOrQZU0Guanw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
