apiVersion: v1
data:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:Q1471S5qBCYbjtq0mjn3zJxknhLqBqzPFrVBEz2FNPNhvpGoTblwjau6DMWMtdZ2Cf7jS29UHufIbVOfE9UAm3rC2aEnK9Ih7Hz7sA+2bgbPTcMQSP2Sda0I10VnDgOBh1F4cD6AKJ76Oof7RGWceT6UNyVlQ8mCnIcUrkOcV7k2XWyq3TAhB6OQuCXMY+2y8hwaBeQhLNQatk9XRtdQqdXKlTjeHHoWjoSrIrKt65JlGdMSXib/ySMNM+cplSPByi9pUO6aeWK2ZNe/ckauO6rwrrDvj2n3a2HsnhtiJJjC/NkFsVvG4UDfxgxoDpp5hivYC4j+1/iWT/aVG3eSJdOjODtVzMiVRis9z4YRf7KL+1uuqckC2B+h5DEPFQrPCzsOTgRFS3XKRkFnzwnPIsykmwDlf5qEoxYWaS2QVkT6L1xXt5O95puq7y1O052SvkFac9V9Zmhs02zaoHnPL2kDTfsLZ4DFy+xMrdjy3CbNmSGqBe8ScHV6GhX7fLZ1lZdS5BrQkoEQ1FXPvHnStdvqnf4HX03+cwbW3VEUxvjNyBIIg4Pe+dxIJ51MLYP8BrlCDHcjCAVpzcpSBp9Km9OiELfQsrLFqi9yfa6THxHDqebfv1H6S+BhthQYa8sJJkbtame/l4XrGVYhCo8pzD0kgWBK4UT2PuqaNm5+WtJOkJkjVtPRBSZb6508T4blPZ7zUA==,iv:Vvi6nunN+hePnL0Q/QwGO83Scz7kJzLfQn2S0GVhrr4=,tag:Whhk4UUudsMmF2m7XcL3uA==,type:str]
kind: Secret
metadata:
    name: sftp-ssh-pk
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUDBUbS8rRUtrYjdtUGhH
            ZmFKazRPWGNEUmlEcVVjeWxXQmljQUNseG53CmppZzhYM0c2SmRjcENSSU5tMGo0
            S0hKTUxERGFJSnhhVGthb0N2d2NPejQKLS0tIHpWcWtFQVJ1SjhuTk1oSit4SlR4
            S21MT1JlSU4rV21kVjhxY3RqbERHU1UKHjjjnztzDyH4WKkQFGcfwUwudNN1qqs8
            2zHiyD2u2XU2i2KriWA7vstMqTNlwst9za5Eu2lej71klqfc4BDksw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-11T09:30:28Z"
    mac: ENC[AES256_GCM,data:4fJRQmbnqjAc0mmSuJs+en6PteBKLriiUx26c68tNJHN1BhP8r23/olD6LYYvIccgsnaqNj6sWP07dBAw5LINSby7pjA56d7zloKc1Q7YYBi7Hy8UONNPjCoJtEPiyPxTzxM25yENfCgzncWKoarvJJO/2GqdN+CWGPa9ox5FPg=,iv:f4R2mmCecF6F5pyHk/X0geVdhlcCMoR0rFI6biijyZo=,tag:M9BXYD/q3fdZDlINhYBX8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
