apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
data:
  run-backup.bash: |
    #!/bin/bash
    set -euo pipefail

    backup_date=$(date '+%Y-%m-%d_%H-%M-%S')
    python manage.py full_backup /tmp/backup_${backup_date}.zip
    cd "${BACKUP_DIR:?}"
    mkdir linkding
    mv /tmp/backup_${backup_date}.zip "${BACKUP_DIR:?}"/linkding/

    echo "Backup was succesful"