apiVersion: v1
data:
    sftp-private-key: ENC[AES256_GCM,data:MUYuQEoIELxBFOntnWiMzPanntjJB9W+RKpOoUK1FGyrfT85+wlMWUewnZbOFWmagRqfgNWgB52NwkwLLhj2BCoE7o7w7Qx+WedFoECnpX9TMTAhSpRnqhgUk7aPw48NxLxiQu3oNFBKoFLHpJ6M8kyRuAD0xHBoMqHshmNa77KHNvzSdmysodvdT7PZhUSkI7oboRaeV6Z6m5zV+P6RDXUIPppe5/MH52OB+9FvgOI6sZ0rv/L8AKPg0GQvENrkEquAdEvU8x/ggINLohFTHC0AekUkemRs3Myjr5qHI46OX7DSI8f5E3pCiOsUbnQF1qEdAr26TpgokB4COjdGwfv+S0nELiTjNUvIRKrzB7XR2Genp4UCsPMWnc5RcaIp8Exj1xQCZ9m8qyWkjJQHsMAjsC1UJkiBRuAhxYXgMMdHOPKcAJsq0/2u/R1y5wvyBfHrsZOvEZbrNimVXGuMf1BJoAITZ7LmSOYJB1XFUDVwlTZ3YS0VFIdijt/DrYDtA4n4FsXjbM2YpcV5yr5p/WmvVQjzEbbMvlAiHyd2e3tdMVzCl3MOzAZwCOIXcLMdc3mBxhMB4KtNkuP8OGUeMkejqFjIAIwR+GpO8+MWLQpPRAcrLzDXYdOHWJQCHr5gXjhTgHl7dXrwhN4eDqNqjbzKQBKEsnJiSRQw94B1mp8ETwc+BE+yEecYu4ZveqR4hykqNtQ2iLNYUK2UL/5uMgh++/g=,iv:J45q521LlJS+xamIV0zZday9T3cW/LDeeaGymY8tREQ=,tag:uzlG95ymaq8m+3ZfuFgzPQ==,type:str]
kind: Secret
metadata:
    name: sftp-private-key
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTnl2WnhqY2swRUxtRXQ1
            WlZHRlo5cDlHZGJYSjgvM2YwTEdIc1ZaNUZRCkJvaGlnbWdHZ0IvVGpaYzhYUE1U
            dXpqZzExNHl6Ukk2MFF3MW1XZCtUMTgKLS0tIGN5RWxzclNrbTRZbzVTQ0R3RUpW
            NTZuWm5OK1NMTkhoK2lEY205dHE4clEKPvDH5ZLFXi/vfRIfSL9FDP9QZKvrJj0p
            4X7kvolbodPcJZf73jtgZcQMToudttfdfO/p3D5BBT0iPb6VkXYplA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-11T11:15:49Z"
    mac: ENC[AES256_GCM,data:6OZY9PDRoEusvdGSQQl/yizv99+mUEHFlTQWNWEJLaiOFNu0OsFM8X8MbUQX0/OAIJ4rrQu0GzjXgw2VSAz9VHZ4BedU44RS7DAbPzcFYJq9KvxUptSkgbuwiancIeCkLrRIPL2WqaDwLTsM1noDegtzopF8fwX7t0bBtPIAn2I=,iv:LF9/5SYGHN8PsYaZHQQ7NbySiv1r5TjbiccVEIYLc00=,tag:0D2AsiUjriSY6siq0x0Urw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
