apiVersion: v1
data:
    password: ENC[AES256_GCM,data:KX9RtWmFlwg=,iv:eNFlpdXJS6Sb5I8O8Yc6N867PIGW0z02EMFOhA/wcKk=,tag:eiRj0l2hQArNn3XYP+UCGg==,type:str]
    user: ENC[AES256_GCM,data:EfYCRNjIYog=,iv:f2PxaqE/vfj9PRk5dPVYJDdobobpbceWx8wPY6LB+oY=,tag:XS0RCw9SvnBkT5JxGbh5qA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OG1jTGhFRDJYMDNrdzB5
            ZnY4UFhvVXY2bW9nZU9BTE1EdlBwd1c4UVdRClBxeHc5ODQ3ZncrRkV4REVyYlhu
            R1YxaWgrM09pbHM0SXJxdHBBU3lQMlEKLS0tIGtDeFNiNmFDVEVVb0JTOUg2Mk1m
            QWh2NlJXZUI1Yi90WmRpQmNiNXhYU28KxvEmIFxVINkJJxoqk69PpFZT5vIkSuXY
            OyWXdurvNyMe07H2nPWvIPOo8+OCyBapGUn1eaONQQI5oz5igoChww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T16:57:38Z"
    mac: ENC[AES256_GCM,data:RCtiebH3JkhuvHVBTCT6vUfWXIkvh5iayMTIS8FU/c4FeIQJF1D0Hj9paqR941AvP3j8rWryJtbUuArgKOWf5GFJNurgoyf3p+9prm/V11Fx/S2IlYv7hAUKHxFruOur59QZmD8NG/LUHV1Wwxo1sk3qm4f0Ha+4G346SDrgpNQ=,iv:7WGxbGfVhi+xYUMCCgDKmM17AMElKieA3y8nnROsAcA=,tag:B/P6gJd4VyH+ihtNTV++Ow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
