apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:SgUaFlInD/Frxbre5/4MbkjUkn/WuYWoTgAAbvNI43PlO12LPksumb3RK42mic/ygee+H01u4uXtdwEgawGKsQTNRiJpINPPHvurkzMAXW80uzPFOB6MQil/n2t6m5+7ocOYF/b9swS8PZZQJ8zP8MH/XbKh1nuRsVLUSrZ25ei0dviBIHhyByzLqk5E5/gTGqbniyyDmBdcAC4K+kE9pTuHw1lHN/hph/S5eqB8winIXeBcbzXsuj14R9ZSQqMTQjueHvIP2dhbOpSWBf+Wa9eL8U22ZQb0lWjBsVL1BSW8uOEvyojzAXWshAI=,iv:J81FtUuORDVxLJmVU8Qb7AI9RCYBNXai+c2Smq+1p7I=,tag:PwVBFw98HTmWo6mktDtT6g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
type: Opaque
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQTBoRGthaE1qQXJjL3l1
            bzRacG55aW93cTB2NkxUbVp4Y044blJhQ1V3CkNGTU5YM1hXS1d4WU5SMS9rMk5J
            cncvdkZlVjFTQ2tnUWRtMzFRdWplNTAKLS0tIEZ6WjAzR0dhTzM3UXBvbHY2b2xF
            dm5qS3VtazVRMndGL0NLc0tDVW54Y28K4V/wZWUo2tn4QGqKmC7tvPztLWmh0yIy
            SV9HzNY/WC7SfZ8HxhHnj+N1Pu4ySxnXtUaZk8UqVehCoCQpuLSCtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:46:49Z"
    mac: ENC[AES256_GCM,data:7BXGVTU4lFMWknGmaNNpi9+6Bqe7k9WmtR9RR44GQceDuRYWlszYxC+Ulszsk+DSOr9cazGpZgEK8lp96guy+5wcdF/ZjdjD6KTaVxxAgfDVOBy2KiVTSFhLmuLERXw8GUZYzuJPXWWXIF6rd21b+QCbo8NaXJh3yf2b+q2tpqk=,iv:FshrZavhX/BIIyACsTH1o3lZYrfArFVF7yW9LfJM6wA=,tag:IxA+qTBzOaXwpTLXXwXPaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
