apiVersion: batch/v1
kind: Job
metadata:
  name: zgrzyt-download-all
  namespace: zgrzyt-ai
spec:
  template:
    spec:
      containers:
        - name: zgrzyt
          image: ghcr.io/mikolajbielinski/zgrzyt-download:main@sha256:2cd191c02f00bb6fa6a7808cc3a2ca5c032f87658efac0ed6436ea946b70cd29
          volumeMounts:
            - mountPath: /podcasts
              name: zgrzyt-podcasts
          envFrom:
            - configMapRef:
                name: zgrzyt-download-all-config
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: zgrzyt-podcasts
          persistentVolumeClaim:
            claimName: zgrzyt-podcasts
      restartPolicy: OnFailure
