apiVersion: batch/v1
kind: Job
metadata:
  name: zgrzyt-download-all
  namespace: zgrzyt-ai
spec:
  activeDeadlineSeconds: 21600
  backoffLimit: 1
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: zgrzyt
          image: ghcr.io/mikolajbielinski/zgrzyt-download:main@sha256:2cd191c02f00bb6fa6a7808cc3a2ca5c032f87658efac0ed6436ea946b70cd29
          volumeMounts:
            - mountPath: /podcasts
              name: zgrzyt-podcasts
          envFrom:
            - configMapRef:
                name: zgrzyt-download-all-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: zgrzyt-podcasts
          persistentVolumeClaim:
            claimName: zgrzyt-podcasts
      restartPolicy: Never
