apiVersion: batch/v1
kind: Job
metadata:
  name: zgrzyt-download-all
  namespace: zgrzyt-ai
spec:
  template:
    spec:
      containers:
        - name: zgrzyt
          image: ghcr.io/mikolajbielinski/zgrzyt-download:main@sha256:bc0f74849a302d856cc468205f29ec24530f600649a4ea030a36affbb49db14f
          volumeMounts:
            - mountPath: /podcasts
              name: zgrzyt-podcasts
          envFrom:
            - configMapRef:
                name: zgrzyt-download-all-config
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: zgrzyt-podcasts
          persistentVolumeClaim:
            claimName: zgrzyt-podcasts
      restartPolicy: OnFailure
