apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '82.18.0'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    alertmanager:
      alertmanagerSpec:
        configSecret: alertmanager-ntfy
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          uid: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
          jsonData:
            maxLines: 1000
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.mbielinski.com
        tls:
          - secretName: grafana-general-tls
            hosts:
              - grafana.mbielinski.com
