apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:9TbcJ5/ZTXgriXTROOFr2hIClTMg9QgboQQcKqFHegI4sbSfw/2AVXoE/Dg3z5RqLdmGPIuGiIeaffDqrcT5e7uTQXWbNCQToqrXzU7ne7eBUTIWI3Da3vh9XoQcVFHzfoa3gTCS3SMaDjtfbOeqhF1rVJ6YEScNHnJqcerwdWbWj21wy21aCixPw1wM90X8gdpKSDvggICs6eqkMYrj7DKDCCvrZw2Ad8cx+gMTuoQ/epvhLRCV2FG10o2EBFQgoYAzkhv5NUD0LpaLnMachrOLcZvlpYsc2iN5UsB0LTBiyP5YUH7EfisKvSo=,iv:SA3RCtgiRkO6HjhElj9iX3kwaPSZoZytWJ4KPVLj1F0=,tag:PgcLBnokCRMu34HjDL2EzA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RzhseWEvWmlkaFJpUU1H
            bzRaRFpXMysyQ3NsTVNwdUtQTEpCd1ZveERvCkxEbk1aTDZoNXdjTm1xak1sNGxW
            ZmZ3TE5rTXdCd2UwN3hjVmw5U2J0eUkKLS0tICt5Q3lRMFdBZjRtRi81b3lESDRX
            eXNVNzBKRU0zb3huZDBZZUdFczlNSE0KrOyB+f1y9sZ8NNi0XGpe95DBEdabidSV
            srYRvDL+8mdHWoDaSIMjCoktiq4ZlLfKKFlv4ObzyEPzXJIN0yrtzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T18:25:15Z"
    mac: ENC[AES256_GCM,data:DRL2F+cCwh5JpWI11vHKtsLlVN95vxoSNNC1dN4VETv1Pl5A85zbgIyvbJj/dgetwcMJS+2DTwYflHzZlIuFT6n6eeGg+OX6bb0uyhTnuVc/UncBWjw7rwDdLbN+OrdjpHMtqhaJd8WxYXX+fMJonI8rytLgjA8uNwiOrhr4TZo=,iv:GHuz9pxfhkZot6SM59QZO22QztFsQjOkxlAo+227K2c=,tag:QIttyewUoOBPPiTy1QOOjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
