apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:TNvt4FPn9mdMyh3a749y1x/X5jFnw66XQOYJae2rEy4bac7Tm0uNqzxXM5qz1GYPOy/8FKDsFVpXLZJPnd1jNKcnXKGWjwVWG4PpK8OupTJ5PYryRR9v4ZI2681WbDeV86Eg/rFgrQM68Yyoq0gJ5SaxC3b1GvY7tILsTxbAPFx24/NqI5oNlBmKQFaYNEsT4OXkwrwmJH/WrMQiXIHyCXGeJpgZbufE4r7MtTIpRzuNiPV1pp+RHLyWfToVs9ypUzaYso4KXoOr7xasQwugE9C1DocuN10yGZIUp+Gk/7XqVvBg6KtGFWb0rWKCsK1gAWL3VSFT7UrwnGSKBDl0i0k9YbjaKqRAEEzKj2yPOh8If0aulkNUl6+1iOL/9kQqgS/PBwMLN884J/K7fkC7cneZFKYUKd0CfcCL2TjCwZ+i6zloz7JwKF6ITA4k1/xXFoeYevHOyH4Va+3ZfL4GaGhdAjuk1xEm9X1gg400zNfhSCiHTNOq/j6szK75cWL3J30SPL3/RBmmPvU5V/Yby2PYqZgdZVWc8HzP3pl9EQYWAc+4+4Im+eA53dY1gDwfeBIF4wxhajG+LLzwbD/jdrvNkQLutioE8MxYcfuKIXATyGKPuo6lZafw/wYEQNxlwtbrgyCy1KAbjj2yDjDW1I2hi0NKgSLVlPGdmOZeQDai5Du3SRu0HakYDfE2QgKq7e6dE1zreQMgv7YDX94wU4ueS6w/sciaqcQIJj9c5jzkAIAvgvxmNEIyrkecGiCp153oZlv6tygZs188bSOihD2WCIAUSyseuQ4R0tVTPAZPqbGBmBQUI627F9axoOKMUkGf0oGoerx/1NpRpxTyc5nZz7aAUavzvX7dZ0lOEXaMakiAK2dVDFLRrfCg1s0aRALvHUYVppD+f5XFyEmu6Afk3dGK5lQcC6Z2CYS0JX5UF/bR3B2mDwIt4X+vpR+/dAJOF0hZB1J45yw7bkpdHyxZLEdnjL5OsSGZkUWAlyPHwph4ii8BlbBdUfvHPqHhUnl7eM6sMhhteJXIwUcx71rKOpW305QBr8GF8HFoFVzW1YXhwe0TdH4IjwcwaOeL/dNf8UakVrHzCHfJQEYjDvP8MIwnqIIhL1j7EuXDZoJtmwC3j+6yaHDJG1UwdFzFqqu15LlPw/967L0MTbtrF+G+8YzWu5yOZTW1bokQY+b4QCkceIFa2FG9W6kvtHi995m5Cz3Ya644HannODOuJNE0nGdWEyHF0QAOejAL/VTKA8K61K9rAIbY6gepo7ws4c6oOrrJK2b0BZBoD3ZA8wif4smxixjRBfYuP9u9UAX7j2JwlEqFl+Tq3MQrXuNkRBX6QaKbvun4SxGppkR3JmBPnOUNiOXW,iv:NeiVtzE6D7Jauao9e+iEMFo2iejKRVgBodIcLCWCLR8=,tag:TXcJedlaAaK9LavkaLylOA==,type:str]
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeEo5OGQ1c0N5YVdwUCtu
            QndwcDg1Z0dZeERlNEF2UEc0NWNITlhUQ3l3CktaYkt2ekZpT0p6cHFXcUt0NVZ0
            WVh4QW12UEhLdmo1RWVUelZNMndwNXcKLS0tIFJlT2ZjbFl4QVhlREJ5TGNrSDFl
            QUlMV1lnNVg0VE5SS1RhaS82N0ZiU1UKbUs/CUncGHd1qNFa5RO1VFD1O8EdX7YW
            ZYvOMN1sPc8wsdwXlm+hlDOtUL4nP/hXkAEln3027vbrJ18mx5RVOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T15:54:42Z"
    mac: ENC[AES256_GCM,data:KqHqkEaFy5BkV30UeyUYcbaPAmnjUn2CrxTT0jQ+jY+lIiq/VirrCL/mZyyKmWgTXJ3RPOVZKdhcPUhzahNs3NEdAJb+Bkro5xPHpfYOHy01Y3b8QQgt2i/UgduTYMXpM+l+MRtcO84zkWo47RssPuCPJI/8IsnTNYIKmjdOoHw=,iv:Anvs7IFH4DaulRShvZplhFVpE/4ZJ3e9aLB7G2uT/28=,tag:IAfGsprQttWvBfc2Vpb5oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
