apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:fPoLVjWZOZfsQ4gF8wGcJ/LXvDU=,iv:JRzlJUS+IrVEhtI7rIetjV9SsKtVuXvHz5wfrt7vUQQ=,tag:SQhXdJZsGEECm0D67BcdYQ==,type:str]
kind: Secret
metadata:
    name: grafana-admin-secret
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbEZPSHg3M255Wjg2Sk1x
            YmFwZzhxc2k4L2k3VkdhWVpUOW03WE5aT2lBCmo5bTRUclgxbER6bFhwb0dlWVU2
            cnQwRjB2dDBuZ3hsdExWRVJXQ21GbVEKLS0tIENCQUwzNTdIR1lLSmRFSTJHc3VI
            SmJleDE5K1NNaXpyTTh0WnRmYUV3VWMKXGz9g0V3F8Jlotorh2tL0cG6ruYFRe40
            GYPecbU4UXdxfV6W9aG+jeZ2DRJb2p4Fa1a2mbMFiIJXv/h1Uegd3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T22:05:22Z"
    mac: ENC[AES256_GCM,data:H/uTOMH3LQiRjFBFTmLgcYrsvJGPq37M8YCpmOqSrbsgaYmenT5q3XtLFjJpSPq41UCboXZ23iuMyueq3yvC508dZ/Glsdp42ge/44Iyf0Aod3x9YQknLGdLhaaEkhVaVmzDenGMmnk8V00QLQ7d7enWwZhG3OujDLHlE8MBeSs=,iv:3Ms3GmpHaZWF6bIXy46pgsznJLgxo/0Dp44vrJZ55RE=,tag:oZB1uqMz9HC/xuzlINiLYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
