apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:6wHxic1+Z2eXwnsMSb3BDvUp6DE=,iv:3627OPN1oulKwEpdokniREr6J4FHjYA8lhcU41BSVNQ=,tag:6LGbfX1zcIMAnTu5aXKxSg==,type:str]
    admin-user: ENC[AES256_GCM,data:8twvY8M32DX7+13d,iv:z5QKPcGd+sQJYPnzhgAp1yzGxeujKAmwgy8QePFwZm4=,tag:xjhIcIsuF2KO6R69BohWOA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-secret
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRE9RSTQ2SkorZ3o2OXFt
            ZDhFRE1Dc0p1eDFWYURJbDFBRmZjcjZCZkJzCkdva0FOZjNjVGlrc1J2N3VvbUVV
            SWVHVG92RitURzZKdGhSNm9sTEpVbFEKLS0tIDFybVRVTjdHcGwxK204SUV6d0E3
            UUYyVEtiVG1zVEgvN05aMWNxTXlabjQK2ZcKfC9s6U1SbUxV5PiybOAMESVma3+Q
            /TBSxd9oFOvPqopuwi61JbyZMNIYdHIIs8+0HY8Oo+jbuJ9lEAqW7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T22:21:57Z"
    mac: ENC[AES256_GCM,data:PxqgIZIWreoENJaFCV1SP4nDvpAitbM3EkSwsXnwuBqYxY8QSrL9gVwowL9ftpeFGGqi3ONS3MUCubx0U1YLquLnoEtfOgtmrrZOzbIbMD93PT8Z/R0mkiSB1xBECporl3VJqj1MvUuzgzjUUvwp2XMNUK/DujuQFfrYq0NIXcY=,iv:ngMogVORTujcKr7NkerSWyhSOti2YreqrxIKwiUM3dk=,tag:tZwjhn/I+P/8Tf/cKdCApQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
