apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:M/V7BCKzxQGi00hE,iv:0h9gdv62Yqnn40d9jGXmFQlKxFl5hGbwL7ic6Gdff0E=,tag:JBAMqKbRnCg7cqhSR9mQVA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:BuhQbn8V7ji3QCkzo8/Hagfq2MY=,iv:x7fctvUNbOGUsjDAj+wrwFKA30Ltu4ZA2qJE1QttXc8=,tag:8qaI70q0UKjcrwODTiMEqA==,type:str]
kind: Secret
metadata:
    name: linkding-superuser
sops:
    age:
        - recipient: age1pz3vjns3q3x8w99w40me3zvnd5nqxkgkeun8cxyg6ct3d3a84avsphsmna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbWJUaThCaCt2ZWVoUFRm
            bFd4Tm9VaFQ2djYzMTZpWHFLcEIyYjJWcFRzCkdtZlBqOHY4dG9XZmkvUy9naUlt
            WHM5TnpscUtWaDZqYzMxeUF2WVhMbW8KLS0tIFd1L2QyYndTaDc4TnNENERETU5k
            VWYzQUJ1djkxalRYWFNLL3dKamtiT0EKsG9og7bpW9HCiLw+c4KIIIatRViwcaeG
            lxZrAFVSrQXJ7f5vTxmvFzATB1XXuhbJBL79dQ/yn87M8wgAHdqXkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:02:12Z"
    mac: ENC[AES256_GCM,data:VvMDN/bSpc76mUVLBzZHyjUuN0hsNjsjOPHMZfIBOMBJhKoQ2y2UpeGmmcPvY/1k0AoMZOqFNNQepbZo3x5pc/nITAt+fPjbhbC8AnZEZebTeZMreYQ7lE3xTvtWm5e8jGzqNBdZLgyo2ujlw9qsjgw/lT6WT0P0dhvlZwsU9vg=,iv:Qd2aArx6tV+6AGgBv0pHefgpKLThkz6PoLtocWLg8v8=,tag:/4ViqfpzTB7fek7U6sAriA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
