apiVersion: v1
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
  RENOVATE_PLATFORM: github
  RENOVATE_X_GITHUB_HOST_RULES: "true"
kind: ConfigMap
metadata:
  name: renovate-configmap
