apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: '0 6 * * *'
  timeZone: Europe/Warsaw
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 21600
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800
      activeDeadlineSeconds: 3600
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: renovate/renovate:44.115.10
              name: renovate
              args:
                - mikolajbielinski/homelab
              envFrom:
                - secretRef:
                    name: renovate-container-env
                - configMapRef:
                    name: renovate-configmap
              resources:
                requests:
                  cpu: 500m
                  memory: 768Mi
                limits:
                  memory: 1536Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
          restartPolicy: Never
